# Main entrypoint of the workflow.
# Pipeline made to follow best practices:
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there.


# ------------------------
#   Load configuration
# ------------------------

configfile: "config/config.yaml"

# ---------------
#   Load rules
# ---------------

include: "rules/common.smk"
include: "rules/short_reads.smk"

localrules: initiate_dbs, short_reads_summary

# ------------------------------------------
#   Define the target outputs for pipeline
# ------------------------------------------

rule all:
    input:
        fastp   = os.path.join(output_dir, "fastp_summary.csv"),
        panres  = os.path.join(output_dir, "panres.csv")
