# Main entrypoint of the workflow.
# Pipeline made to follow best practices:
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there.

import os
from snakemake.shell import shell
shell.executable("/bin/bash")

wildcard_constraints:
    sample = "[^/]+"

# ------------------------
#   Load configuration
# ------------------------

configfile: "config/config.yaml"

# ---------------
#   Load rules
# ---------------

include: "rules/common.smk"
include: "rules/short_reads.smk"
include: "rules/contigs.smk"

localrules: initiate_dbs, short_reads_summary, init_genomad

# ------------------------------------------
#   Define the target outputs for pipeline
# ------------------------------------------

rule all:
    input:
        fastp        = os.path.join(output_dir, "fastp_summary.csv"),
        short_reads  = os.path.join(output_dir, "short_reads_output.csv"),
        contigs      = expand(os.path.join(output_dir, "data", "megahit", "{sample}.contigs.fa"), sample=samples),
        genomad      = expand(os.path.join(output_dir, "data", "genomad", "{sample}"), sample=samples)
