#!/usr/bin/env python3
"""
detect_circular_contigs.py

Determine circularity of contigs from a read mapping BAM/SAM file according to the
algorithm described in https://doi.org/10.1038/s41564-024-01610-3.
This script was generated by GitHub Copilot (GPT-5 mini)

Algorithm summary (implemented):
- For each contig in the BAM header:
  - Collect mapping intervals of all primary alignments to compute "detection" (fraction
    of bases covered by at least one read).
  - Iterate paired reads mapped to this contig (only primary alignments, skip supplementary/secondary).
    - For pairs where both reads map to the same contig:
      - Determine upstream (smaller start) and downstream (larger start).
      - Determine orientation:
          forward-reverse: upstream.is_reverse == False and downstream.is_reverse == True
          reverse-forward: upstream.is_reverse == True and downstream.is_reverse == False
      - Compute:
          insert = downstream_start - upstream_end
          gap   = downstream_end - upstream_start
      - Collect:
          - inserts for forward-reverse pairs (for median insert)
          - gaps for reverse-forward pairs
  - Compute median insert from forward-reverse inserts.
  - Compute D = contig_length - 3 * median_insert.
  - Label contig as circular if:
      detection >= min_detection (default 0.95) AND
      at least one reverse-forward gap >= D

Example:
  ./detect_circular_contigs.py -b sample.mapped.bam -o circularity.tsv

"""

from __future__ import annotations
import argparse
import os
import sys
import statistics
from collections import defaultdict
from typing import List, Tuple, Dict, Optional

try:
    import pysam
except Exception as e:
    sys.stderr.write("ERROR: pysam is required. Install with `pip install pysam`.\n")
    raise

def merge_intervals(intervals: List[Tuple[int, int]]) -> List[Tuple[int, int]]:
    """Merge [start, end) intervals. Returns merged list sorted by start."""
    if not intervals:
        return []
    intervals_sorted = sorted(intervals, key=lambda x: x[0])
    merged = []
    cur_start, cur_end = intervals_sorted[0]
    for s, e in intervals_sorted[1:]:
        if s <= cur_end:  # overlap or contiguous
            cur_end = max(cur_end, e)
        else:
            merged.append((cur_start, cur_end))
            cur_start, cur_end = s, e
    merged.append((cur_start, cur_end))
    return merged

def median_or_none(values: List[float]) -> Optional[float]:
    if not values:
        return None
    return statistics.median(values)

def analyze_contig(alnfile: pysam.AlignmentFile, contig: str, contig_len: int, min_detection: float
                  ) -> Dict[str, object]:
    """
    Process a single contig by fetching reads mapped to it.

    Returns a dict with stats used for circularity decision.
    """
    intervals: List[Tuple[int, int]] = []
    mate_buffer: Dict[str, pysam.AlignedSegment] = {}
    forward_reverse_inserts: List[int] = []
    reverse_forward_gaps: List[int] = []
    n_fr_pairs = 0
    n_rf_pairs = 0

    for read in alnfile.fetch(contig):
        if read.is_unmapped or read.is_secondary or read.is_supplementary:
            continue

        start = read.reference_start
        end = read.reference_end
        if start is None or end is None or end <= start:
            continue
        intervals.append((start, end))

        if not read.is_paired or read.mate_is_unmapped:
            continue

        qname = read.query_name
        prev = mate_buffer.get(qname)
        if prev is None:
            mate_buffer[qname] = read
            continue
        else:
            mate = prev
            del mate_buffer[qname]

            if read.reference_start < mate.reference_start:
                up = read
                down = mate
            elif mate.reference_start < read.reference_start:
                up = mate
                down = read
            else:
                if read.reference_end <= mate.reference_end:
                    up = read
                    down = mate
                elif mate.reference_end < read.reference_end:
                    up = mate
                    down = read
                else:
                    continue

            up_rev = up.is_reverse
            down_rev = down.is_reverse

            up_start = up.reference_start
            up_end = up.reference_end
            down_start = down.reference_start
            down_end = down.reference_end

            insert = down_start - up_end
            gap = down_end - up_start

            if (not up_rev) and down_rev:
                forward_reverse_inserts.append(insert)
                n_fr_pairs += 1

            if up_rev and (not down_rev):
                reverse_forward_gaps.append(gap)
                n_rf_pairs += 1

    merged = merge_intervals(intervals)
    covered_bases = sum(e - s for s, e in merged)
    detection = covered_bases / contig_len if contig_len > 0 else 0.0

    median_insert = median_or_none(forward_reverse_inserts)
    max_rf_gap = max(reverse_forward_gaps) if reverse_forward_gaps else None

    D = None
    if median_insert is not None:
        D = contig_len - 3.0 * median_insert

    circular = False
    if detection >= min_detection and D is not None and reverse_forward_gaps and any(g >= D for g in reverse_forward_gaps):
        circular = True

    return {
        "contig": contig,
        "contig_len": contig_len,
        "detection": detection,
        "median_insert": median_insert,
        "D": D,
        "circular": circular,
    }

def main(argv=None):
    parser = argparse.ArgumentParser(description="Detect circular contigs from a read mapping (BAM/SAM).")
    parser.add_argument("-b", "--bam", required=True, help="BAM/SAM file with reads mapped to contigs (paired-end).")
    parser.add_argument("-o", "--out", required=True, help="Output plain text file: contig<TAB>0/1 per line (no header).")
    parser.add_argument("--min-detection", type=float, default=0.95, help="Minimum detection threshold (default 0.95).")
    parser.add_argument("--contig", help="Optional: only analyze a single contig name.")
    parser.add_argument("--min-covered-bases", type=int, default=1, help="Minimum contig length to consider (default 1).")
    args = parser.parse_args(argv)

    if not os.path.exists(args.bam):
        sys.exit(f"ERROR: BAM/SAM file not found: {args.bam}")

    try:
        alnfile = pysam.AlignmentFile(args.bam, "rb")
    except ValueError:
        alnfile = pysam.AlignmentFile(args.bam, "r")

    references = alnfile.references
    lengths = alnfile.lengths
    contig_info = list(zip(references, lengths))

    if args.contig:
        contig_info = [(c, l) for c, l in contig_info if c == args.contig]
        if not contig_info:
            sys.exit(f"ERROR: contig {args.contig} not found in BAM header.")

    results = []
    for contig, clen in contig_info:
        if clen < args.min_covered_bases:
            continue
        sys.stderr.write(f"Processing contig {contig} (len={clen})...\n")
        res = analyze_contig(alnfile, contig, clen, args.min_detection)
        results.append(res)

    alnfile.close()

    # Write simplified output: contig<TAB>0|1 per line, no header
    with open(args.out, "w") as fh:
        for r in results:
            val = "1" if r["circular"] else "0"
            fh.write(f"{r['contig']}\t{val}\n")

    sys.stderr.write(f"Done. Simplified results written to {args.out}\n")

if __name__ == "__main__":
    main()